<a href="https://colab.research.google.com/github/m-zayed5722/Misc_Projects/blob/main/Code_Testing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf


In [ ]:
import string
import random


In [ ]:
def sum_array(arr):
    # Initialize a variable to keep track of the sum
    total = 0

    # Using a variable to skip numbers if needed
    skip = False

    # Traverse through the array
    i = 0
    while i < len(arr):
        # If the current number is 6 and the skip flag is False
        if arr[i] == 6 and not skip:
            # Try to find the next 7 in the array
            if 7 in arr[i+1:]:
                # Set the index i to the position after 7
                i = arr.index(7, i+1) + 1
                # Set the skip flag to True to avoid considering any numbers between 6 and 7
                skip = True
                continue
        # If the current number is not 6 or if the skip flag is False
        if not skip:
            print (arr[i])
            total += arr[i]
        i += 1

    return total

# Example usage
arr = [1, 2, 3, 6, 4, 5, 7, 8]
print(sum_array(arr))  # Expected output: 1+2+3+8 = 14

1
2
3
6


In [ ]:


def generate_password(length):
    """
    Generates a random password with uppercase, lowercase, numbers, and special characters.

    Args:
        length: The desired length of the password.

    Returns:
        A string representing the generated password.
    """

    # Combine all character sets
    characters = string.ascii_letters + string.digits + string.punctuation

    # Ensure at least one character from each category
    password = []
    required_chars = [
        random.choice(string.ascii_lowercase),
        random.choice(string.ascii_uppercase),
        random.choice(string.digits),
        random.choice(string.punctuation)
    ]
    password.extend(required_chars)
    # Fill the rest with random characters
    for _ in range(length - 4):
        password.append(random.choice(characters))

    # Shuffle to avoid predictable patterns
    random.shuffle(password)

    return ''.join(password)


!I[(fE2oGA$0


In [ ]:
print(generate_password(12))  # Example output: i69D@&,9@czm

21_1U~1pHyUI


In [ ]:
def generate_password(length):
    # Ensure required character types
    lowercase = string.ascii_lowercase
    uppercase = string.ascii_uppercase
    digits = string.digits
    symbols = string.punctuation

    # Guarantee at least one character from each category
    password = random.choice(lowercase) + random.choice(uppercase) + \
               random.choice(digits) + random.choice(symbols)

    # Fill remaining characters
    remaining_length = length - 4  # Account for the guaranteed characters
    all_chars = lowercase + uppercase + digits + symbols
    for _ in range(remaining_length):
        password += random.choice(all_chars)

    # Shuffle for better security
    password_list = list(password)
    random.shuffle(password_list)
    password = ''.join(password_list)

    return password

In [ ]:
print(generate_password(12))  # Example output: i69D@&,9@czm

imzgvGV|`9;W


In [ ]:

@tf.custom_gradient
def grad_reverse(x):
  y = tf.identity(x)
  def custom_grad(dy):
    return -dy
  return y, custom_grad

# Example input (tensor)
input_tensor = tf.constant([[1.0, 2.0], [3.0, 4.0]])

with tf.GradientTape() as tape:
  reversed_tensor = grad_reverse(input_tensor)  # Gradient will be reversed
  output = tf.reduce_sum(reversed_tensor)     # Example follow-up operation

# Calculate the gradient (which will use the reversed gradient from grad_reverse)
grad = tape.gradient(output, input_tensor)

print("Original input tensor: \n", input_tensor)
print("Output of grad_reverse: \n", reversed_tensor)
print("Gradient (reversed): \n", grad)


Original input tensor: 
 tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
Output of grad_reverse: 
 tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
Gradient (reversed): 
 None


In [ ]:
# Define the custom gradient function
@tf.custom_gradient
def grad_reverse(x):
    y = tf.identity(x)

    # Define the custom gradient function
    def custom_grad(dy):
        return -dy

    return y, custom_grad

# Example input (tensor)
input_tensor = tf.constant([[1.0, 2.0], [3.0, 4.0]])

with tf.GradientTape() as tape:
    # Apply grad_reverse to the reduction operation
    reversed_tensor = tf.reduce_sum(grad_reverse(input_tensor))
    output = tf.reduce_sum(reversed_tensor)  # Example follow-up operation

# Calculate the gradient (which will use the reversed gradient from grad_reverse)
grad = tape.gradient(output, input_tensor)

print("Original input tensor: \n", input_tensor)
print("Output of grad_reverse: \n", reversed_tensor)
print("Gradient (reversed): \n", grad)

Original input tensor: 
 tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
Output of grad_reverse: 
 tf.Tensor(10.0, shape=(), dtype=float32)
Gradient (reversed): 
 None


In [ ]:

# Define the custom gradient function
@tf.custom_gradient
def grad_reverse(x):
    y = tf.identity(x)

    # Define the custom gradient function
    def custom_grad(dy):
        return -dy

    return y, custom_grad

# Example input tensor
x = tf.constant(2.0)

# Forward pass: Get the output of the function
with tf.GradientTape() as tape:
    tape.watch(x)
    y = grad_reverse(x)

# Compute the gradient using automatic differentiation
grad = tape.gradient(y, x)

print("Input:", x.numpy())
print("Output (Forward Pass):", y.numpy())
print("Gradient:", grad.numpy())

Input: 2.0
Output (Forward Pass): 2.0
Gradient: -1.0


In [ ]:

@tf.custom_gradient
def grad_reverse(x):
    y = tf.identity(x)

    # Define the custom gradient function
    def custom_grad(dy):
        return -dy

    return y, custom_grad

# Example input (tensor)
input_tensor = tf.constant([[1.0, 2.0], [3.0, 4.0]])

with tf.GradientTape() as tape:
    # Apply grad_reverse to the reduction operation
    output = tf.reduce_sum(grad_reverse(input_tensor))

# Calculate the gradient (which will use the reversed gradient from grad_reverse)
grad = tape.gradient(output, input_tensor)

print("Original input tensor: \n", input_tensor)
print("Output of grad_reverse: \n", output)  # Output is directly the output of grad_reverse
print("Gradient (reversed): \n", grad)


Original input tensor: 
 tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
Output of grad_reverse: 
 tf.Tensor(10.0, shape=(), dtype=float32)
Gradient (reversed): 
 None


In [ ]:

@tf.custom_gradient
def grad_reverse(x):
    y = tf.identity(x)

    # Define the custom gradient function
    def custom_grad(dy):
        return -dy

    return y, custom_grad


# Example input (tensor)
input_tensor = tf.constant([[1.0, 2.0], [3.0, 4.0]])


with tf.GradientTape() as tape:
    tape.watch(input_tensor)  # Ensure input_tensor is watched by the tape
    # Apply grad_reverse to the reduction operation
    output = tf.reduce_sum(grad_reverse(input_tensor))


# Calculate the gradient (which will use the reversed gradient from grad_reverse)
grad = tape.gradient(output, input_tensor)

print("Original input tensor: \n", input_tensor)
print("Output of grad_reverse: \n", output)  # Output is directly the output of grad_reverse
print("Gradient (reversed): \n", grad)


Original input tensor: 
 tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
Output of grad_reverse: 
 tf.Tensor(10.0, shape=(), dtype=float32)
Gradient (reversed): 
 tf.Tensor(
[[-1. -1.]
 [-1. -1.]], shape=(2, 2), dtype=float32)


In [ ]:

@tf.custom_gradient
def grad_reverse(x):
  y = tf.identity(x)
  def custom_grad(dy):
    return -dy
  return y, custom_grad

# Example input (tensor)
input_tensor = tf.constant([[1.0, 2.0], [3.0, 4.0]])

with tf.GradientTape() as tape:
  tape.watch(input_tensor)
  reversed_tensor = grad_reverse(input_tensor)  # Gradient will be reversed
  output = tf.reduce_sum(reversed_tensor)     # Example follow-up operation

# Calculate the gradient (which will use the reversed gradient from grad_reverse)
grad = tape.gradient(output, input_tensor)

print("Original input tensor: \n", input_tensor)
print("Output of grad_reverse: \n", reversed_tensor)
print("Gradient (reversed): \n", grad)

Original input tensor: 
 tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
Output of grad_reverse: 
 tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
Gradient (reversed): 
 tf.Tensor(
[[-1. -1.]
 [-1. -1.]], shape=(2, 2), dtype=float32)


In [ ]:
@tf.custom_gradient
def grad_reverse(x):
    y = tf.identity(x)
    def custom_grad(dy):
        return -dy
    return y, custom_grad

# Define the function g(x) = grad_reverse(x^2)
def g(x):
    return grad_reverse(x**2)

# Use a TensorFlow Variable for x and set its initial value to 3
x = tf.Variable(3.0)

with tf.GradientTape() as tape:
    y = g(x)

# Compute gradient dy/dx
grad = tape.gradient(y, x)

print(grad.numpy())

In [ ]:
@tf.custom_gradient
def grad_reverse(x):
    y = tf.identity(x)

    # Define the custom gradient function
    def custom_grad(dy):
        return -dy

    return y, custom_grad

# Define the function g(x) = grad_reverse(x^2)
def g(x):
    return grad_reverse(x**2)

# Input tensor
input_tensor = tf.constant([[1.0, 2.0], [3.0, 4.0]])

# Apply the function g to the input tensor
with tf.GradientTape() as tape:
    tape.watch(input_tensor)  # Ensure input_tensor is watched by the tape
    y = g(input_tensor)

# Compute gradient dy/dx
grad = tape.gradient(y, input_tensor)

print(grad.numpy())


[[-2. -4.]
 [-6. -8.]]


In [ ]:
def binary_search(arr, target):
    """
    Performs a binary search for a target element in a sorted list.
    Returns the index of the target if found, otherwise returns -1.
    """
    low = 0
    high = len(arr) - 1

    while low <= high:
        mid = (low + high) // 2
        guess = arr[mid]
        if guess == target:
            return mid
        if guess > target:
            high = mid - 1
        else:
            low = mid + 1

    return -1

def main():
    try:
        user_list = input("Enter a sorted list of numbers separated by spaces: ")
        numbers = [int(item) for item in user_list.split()]

        target = int(input("Enter the number to search for: "))

        result = binary_search(numbers, target)
        if result != -1:
            print(f"Number found at index: {result}")
        else:
            print("Number not found in the list.")

    except ValueError:
        print("Invalid input. Please enter only numbers.")



Enter a sorted list of numbers separated by spaces: 1 2 3 4 5 6
Enter the number to search for: 3
Number found at index: 2


In [ ]:
if __name__ == "__main__":
    main()

Enter a sorted list of numbers separated by spaces: 2 66 333 9877
Enter the number to search for: 2
Number found at index: 0


In [ ]:

data = {'col1': [1, 2, 3], 'col2': [4, 5, 6]}
df = pd.DataFrame(data)

# Create a new column with a list of values
df['new_col'] = [10, 20, 30]
print(df)

# Or use an existing Series:
new_series = pd.Series([-1, -2, -3])
df['another_col'] = new_series
print(df)


   col1  col2  new_col
0     1     4       10
1     2     5       20
2     3     6       30
   col1  col2  new_col  another_col
0     1     4       10           -1
1     2     5       20           -2
2     3     6       30           -3


In [ ]:
# Insert at the beginning (index 0)
df.insert(0, 'new_col1', [7, 8, 9])
print(df)

   new_col1  col1  col2  new_col  another_col
0         7     1     4       10           -1
1         8     2     5       20           -2
2         9     3     6       30           -3


In [ ]:
# Create a new DataFrame with the added column
new_df = df.assign(new_col=[-10, -20, -30])
print(new_df)

   new_col1  col1  col2  new_col  another_col
0         7     1     4      -10           -1
1         8     2     5      -20           -2
2         9     3     6      -30           -3


In [ ]:
new_cols_dict = {'new_col1': [1, 2, 3], 'new_col2': [4, 5, 6]}
df = df.assign(**new_cols_dict)
print(df)

   new_col1  col1  col2  new_col  another_col  new_col2
0         1     1     4       10           -1         4
1         2     2     5       20           -2         5
2         3     3     6       30           -3         6


In [ ]:

def calculate_new_column(row):
    return row['col1'] * row['col2']  # Calculate based on existing columns

df['calculated_col'] = df.apply(calculate_new_column, axis=1)
print(df)

   new_col1  col1  col2  new_col  another_col  new_col2  calculated_col
0         1     1     4       10           -1         4               4
1         2     2     5       20           -2         5              10
2         3     3     6       30           -3         6              18


In [ ]:

# Create a sample DataFrame
data = {
    'A': [1, 2, 3],
    'B': [4, 5, 6]
}
df = pd.DataFrame(data)

# Print the original DataFrame
print("Original DataFrame:")
print(df)

# Manually add a new column
df['C'] = [7, 8, 9]

# Print the DataFrame with the new column
print("\nDataFrame after adding the new column:")
print(df)


Original DataFrame:
   A  B
0  1  4
1  2  5
2  3  6

DataFrame after adding the new column:
   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9


In [ ]:
def sum_array(arr):
    # Initialize a variable to keep track of the sum
    total = 0

    # Using a variable to skip numbers if needed
    skip = False

    # Traverse through the array
    i = 0
    while i < len(arr):
        # If the current number is 6 and the skip flag is False
        if arr[i] == 6 and not skip:
            # Try to find the next 7 in the array
            next_seven_index = -1
            for j in range(i+1, len(arr)):
                if arr[j] == 7:
                    next_seven_index = j
                    break

            # If a 7 is found after the current index
            if next_seven_index != -1:
                # Set the index i to the position after 7
                i = next_seven_index + 1
                # Set the skip flag to True to avoid considering any numbers between 6 and 7
                skip = True
                continue
        # If the current number is not 6 or if the skip flag is False
        if not skip:
            total += arr[i]
        # Reset the skip flag to False once the sequence of 6 followed by 7 is completed
        if skip and arr[i] == 7:
            skip = False
        i += 1

    return total

# Example usage
arr = [1, 2, 3, 6, 4, 5, 7, 8]
print(sum_array(arr))  # Expected output: 1+2+3+8 = 14

6


In [ ]:
#design a phase 3 warden phases code from osrs

#create 2D board as the closed area
#simulate the game between player and monster

#function to attack and scan area
#check half area then other half then middle

#player able to move adjacent

#add other attacks
